### ISSUE TITLE
vmodes minor cleaning up and improvement

### ISSUE THREAD

**Issue by apatlpo** [slgentil/croco#24]
**Projections**. 

API could be somewhat clarified I believe. When one wants to project onto modes there are several cases:

- 1D vertical modes: all goes well, in other words, the data horizontal grid does not matter

- horizontally varying modes: in that case, data needs to be interpolated horizontally first on the vertical mode grid, otherwise the projection will broadcast horizontal dimensions that differ. If this statement is correct we need to more explicitly state this in the docstring. Right now it is unclear whether this horizontal interpolation may be performed within the call to `project`or not. The notebook for example falsely lead to believe it is the case, as `z_rho` (on hgrid rho) is passed to project.

**very minor detail**:

- `vmodes.ipynb ` / cell 28: set aspect to equal (`subplot_kws={'aspect':'equal'}`)

**Comment by NoeLahaye** [comment]
Since you opened this issue, I have a question / suggestion on `load_vmodes`:

* `persist`is passed to Vmodes as is because the dataset is subsequently re-assigned? Otherwise, when persisting an object, even when not using it or triggering its computation explicitly, dask can launch the corresponding task if it's doing nothing, right?
* this line is False, I think:
https://github.com/slgentil/croco/blob/c16668cae8b354a84c7ee2e85e475e3640045b9e/crocosi/vmodes.py#L519
should read `projections = projections.persist()`

**Comment by NoeLahaye** [comment]
>     * Right now it is unclear whether this horizontal interpolation may be performed within the call to `project`or not.

I did not intent to have horizontal projections performed inside `Vmodes`. Either we should add this functionality in the class and methods -- if we think it is necessary, either we make it very clear in the API and example notebook. As far as I'm concerned, I don't need it (because I do mostly weird projections that mix different grids anyway)

**Comment by apatlpo** [comment]
- [ ] doc and tests for horizontal grid interpolations
- [X] update `vmodes.ipynb`
- [X] `ds_proj = projections.persist()`corrected

**Comment by apatlpo** [comment]
relevant PR is #25
